# Generated by Django 4.1.5 on 2025-04-15 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('idUser', models.CharField(max_length=100)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 4, 15, 21, 42, 58, 258146, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
