# Generated by Django 4.1.5 on 2025-06-13 00:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('idLog', models.AutoField(primary_key=True, serialize=False)),
                ('id_user', models.CharField(max_length=100)),
                ('log_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('list_action', models.JSONField(default=list)),
            ],
        ),
    ]
