# Generated by Django 4.1.5 on 2025-04-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actionLogging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
