# Generated by Django 4.1.5 on 2025-05-06 01:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actionLogging', '0002_alter_actionlog_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actionlog',
            old_name='idUser',
            new_name='id_user',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='action',
        ),
        migrations.RemoveField(
            model_name='actionlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='actionlog',
            name='list_action',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='actionlog',
            name='log_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
